name: CI of Eigen3ToPython

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest]
        build-type: [Debug, RelWithDebInfo]
        exclude:
          # No Debug build in Windows
          - os: windows-latest
            build-type: Debug

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: cython cython3 python-nose python3-nose python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools libeigen3-dev
        macos: |
          brew: eigen
          pip: Cython coverage nose numpy
        windows: |
          pip: Cython coverage nose numpy
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        build-type: ${{ matrix.build-type }}
#    - name: Slack Notification
#      uses: homoluctus/slatify@master
#      if: always()
#      with:
#        type: ${{ job.status }}
#        job_name: 'Build ${{ matrix.os }}'
#        mention_if: 'always'
#        username: "GitHub Actions Report"
#        channel: '#ci'
#        url: ${{ secrets.SLACK_WEBHOOK }}
