name: CI of Eigen3ToPython

on: [push,pull_request]

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        ubuntu: |
          apt: cython cython3 python-nose python3-nose python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools libeigen3-dev
        macos: |
          brew: eigen
          pip: Cython coverage nose numpy
        windows: |
          pip: Cython coverage nose numpy
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_BINDING_BUILD_PYTHON2_AND_PYTHON3:BOOL=ON || exit 1
      if: matrix.os != 'windows-latest'
    - name: Configure (Windows)
      shell: cmd
      run: |
        md build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="C:\devel\install"
      if: matrix.os == 'windows-latest'
    - name: Build
      shell: bash
      run: cmake --build . --config RelWithDebInfo || exit 1
      working-directory: ./build
    - name: Install
      shell: bash
      run: cmake --build . --target install --config RelWithDebInfo || exit 1
      working-directory: ./build
    - name: Test
      shell: bash
      run: ctest -C RelWithDebInfo || exit 1
      working-directory: ./build
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: 'Build ${{ matrix.os }}'
        mention_if: 'always'
        username: "GitHub Actions Report"
        channel: '#ci'
        url: ${{ secrets.SLACK_WEBHOOK }}
