name: CI of Eigen3ToPython

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
        build-type: [Debug, RelWithDebInfo]
        exclude:
          # No Debug build in Windows
          - os: windows-latest
            build-type: Debug

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install pip for Python 2 (Ubuntu 20.04)
      run: |
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
        sudo python2 get-pip.py
        rm -f get-pip.py
      if: matrix.os == 'ubuntu-20.04'
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: cython cython3 python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools python-pytest python3-pytest libeigen3-dev
        macos: |
          brew: eigen
          pip: Cython coverage nose numpy pytest setuptools
        windows: |
          pip: Cython coverage nose numpy pytest
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        build-type: ${{ matrix.build-type }}
      env:
        ARCHFLAGS: "-arch arm64"
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          Build *${{ matrix.os }}/${{ matrix.build-type }}* failed on ${{ github.ref }}
