name: Package Eigen3ToPython

# This workflow only runs when pushing to master or pushing a tag
#
# On master, it will:
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact-head
#
# On tagged versions it will:
# - Create a GitHub release draft
# - Attach the sources to the release
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact
# - Finalize the release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-packages:

    strategy:
      matrix:
        dist: [xenial]
        arch: [amd64]

    runs-on: ubuntu-18.04
    env:
      DEBFULLNAME: JRL/IDH Continuous Integration Tool
      DEBEMAIL: jrl-idh+ci@gmail.com
      DIST: ${{ matrix.dist }}
      ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup pbuilder
      run: |
        set -x
        ls -la
        sudo apt-get update -qq
        sudo apt-get install -qq packaging-dev debootstrap devscripts git-buildpackage debian-archive-keyring unzip pkg-kde-tools dput python3-setuptools python-pip python3-pip git-build-recipe python-all python3-all cython cython3 python-nose python3-nose python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools libeigen3-dev
        cp -f .github/workflows/pbuilderrc $HOME/.pbuilderrc
        ls -la $HOME
        sed -i "s/@DIST@/${DIST}/g" $HOME/.pbuilderrc
        sed -i "s/@ARCH@/${ARCH}/g" $HOME/.pbuilderrc
        sed -i "s/@ROS_SETUP@//g" $HOME/.pbuilderrc
        sed -i "s/@OTHERMIRRORS@//g" $HOME/.pbuilderrc
        sudo pbuilder create
        echo "echo \"force-unsafe-io\" > /etc/dpkg/dpkg.cfg.d/02apt-speedup" | sudo pbuilder login --save-after-exec
        sudo pbuilder update
    - name: Build recipe
      run: |
        set -x
        git config --global user.name "${DEBFULLNAME}"
        git config --global user.email "${DEBEMAIL}"
        cp .github/workflows/Eigen3ToPython.recipe /tmp/Eigen3ToPython.recipe
        export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        sed -i "s#@REF@#${REF}#" /tmp/Eigen3ToPython.recipe
        echo "Using the following recipe"
        echo "##########################"
        cat /tmp/Eigen3ToPython.recipe
        git-build-recipe --allow-fallback-to-native /tmp/Eigen3ToPython.recipe /tmp/pbuilder
    - name: Build package
      run: |
        sudo pbuilder build /tmp/pbuilder/*.dsc
    - uses: actions/upload-artifact@v1
      with:
        name: package-${{ matrix.dist }}-${{ matrix.arch }}
        path: /var/cache/pbuilder/${{ matrix.dist }}-${{ matrix.arch }}/result/
