name: Package Eigen3ToPython

# This workflow only runs when pushing to master or pushing a tag
#
# On master, it will:
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact-head
#
# On tagged versions it will:
# - Create a GitHub release draft
# - Attach the sources to the release
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact
# - Finalize the release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-packages:

    strategy:
      matrix:
        dist: [xenial]
        arch: [amd64]

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Prepare recipe
      run: |
        set -x
        cp .github/workflows/Eigen3ToPython.recipe /tmp/Eigen3ToPython.recipe
        export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        sed -i "s#@REF@#${REF}#" /tmp/Eigen3ToPython.recipe
        if [ $REF == "master" ]
        then
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-head"
        else
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-release"
        fi
        echo "Prepared recipe"
        echo "###############"
        cat /tmp/Eigen3ToPython.recipe
    - name: Build package
      uses: jrl-umi3218/github-actions/build-package@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        recipe: /tmp/Eigen3ToPython.recipe
        other-mirrors: ${{ env.EXTRA_MIRROR }}
        other-gpg-keys: "0x892EA6EE273707C6495A6FB6220D644C64666806"
    - uses: actions/upload-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
        path: /tmp/packages-${{ matrix.dist }}-${{ matrix.arch }}/

  upload-packages:
    needs: build-packages
    strategy:
      matrix:
        dist: [xenial]
        arch: [amd64]

    runs-on: ubuntu-18.04
    steps:
    - name: Set upload URL (master)
      run: |
        echo "::set-env name=BINTRAY_URL::api.bintray.com/content/gergondet/multi-contact-head"
        echo "::set-env name=VERSION_NAME::HEAD"
      if: github.ref == 'refs/heads/master'
    - name: Set upload URL (tag)
      run: |
        echo "::set-env name=BINTRAY_URL::api.bintray.com/content/gergondet/multi-contact-release"
        export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        echo "::set-env name=VERSION_NAME::${REF}"
      if: github.ref != 'refs/heads/master'
    - name: Download packages
      uses: actions/download-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
    - name: Upload
      run: |
        set -x
        cd packages-${{ matrix.dist }}-${{ matrix.arch }}
        for f in `ls *.deb`
        do
          curl -T $f -ugergondet:${{ secrets.BINTRAY_API_KEY }} "https://${BINTRAY_URL}/Eigen3ToPython/${VERSION_NAME}/${{ matrix.dist }}/${{ matrix.arch }}/$f;deb_distribution=${{ matrix.dist }};deb_component=main;deb_architecture=${{ matrix.arch }};publish=1;override=1" --header "X-GPG-PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}"
        done
