name: Package Eigen3ToPython

# This workflow only runs when pushing to master or pushing a tag
#
# On master, it will:
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact-head
#
# On tagged versions it will:
# - Create a GitHub release draft
# - Attach the sources to the release
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact
# - Finalize the release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-packages:

    strategy:
      matrix:
        dist: [xenial]
        arch: [amd64]

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Prepare recipe
      run: |
        set -x
        cp .github/workflows/Eigen3ToPython.recipe /tmp/Eigen3ToPython.recipe
        export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        sed -i "s#@REF@#${REF}#" /tmp/Eigen3ToPython.recipe
        if [ $REF == "master" ]
        then
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-head"
        else
          echo "::set-env name=EXTRA_MIRROR::https://dl.bintray.com/gergondet/multi-contact-release"
        fi
        echo "Prepared recipe"
        echo "###############"
        cat /tmp/Eigen3ToPython.recipe
    - name: Build package
      uses: jrl-umi3218/github-actions/build-package@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        recipe: /tmp/Eigen3ToPython.recipe
        other-mirrors: ${{ env.EXTRA_MIRROR }}
        other-gpg-keys: "0x892EA6EE273707C6495A6FB6220D644C64666806"
    - uses: actions/upload-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
        path: /tmp/packages-${{ matrix.dist }}-${{ matrix.arch }}/

  upload-packages:
    needs: build-packages
    strategy:
      matrix:
        dist: [xenial]
        arch: [amd64]

    runs-on: ubuntu-18.04
    steps:
    - name: Set upload parameters
      run: |
        export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        if [ $REF == "master" ]
        then
          echo "::set-env name=BINTRAY_REPO::multi-contact-head"
          echo "::set-env name=BINTRAY_VERSION::HEAD"
        else
          echo "::set-env name=BINTRAY_REPO::multi-contact-release"
          echo "::set-env name=BINTRAY_VERSION::${REF}"
        fi
    - name: Download packages
      uses: actions/download-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
    - name: Upload
      uses: jrl-umi3218/github-actions/upload-package@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        subject: gergondet
        repo: ${{ env.BINTRAY_REPO }}
        package: |
          name: Eigen3ToPython
          desc: "This package provides a bi-directional bridge between numpy and Eigen using Cython"
          licenses: [BSD 2-Clause]
          vcs_url: https://github.com/${{ github.repository }}
        version: ${{ env.BINTRAY_VERSION }}
        path: packages-${{ matrix.dist }}-${{ matrix.arch }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
